In [ ]:
import numpy as np
x=np.array([1,2,3,4,2])
print(np.sort(x))

[1 2 2 3 4]

In [ ]:
y=np.array([1,2,3,4,5])
z=[True,False,True,False,True]
print(y[z])

[1 3 5]

In [ ]:
print(x.mean())
print(x.std())
print(x.var())
print(x.sum())
print(x.min())
print(x.max())

2.4
1.019803902718557
1.04
12
1
4

In [ ]:
#weighted mean
x=np.array([1,2,3,4,5])
w=np.array([1,2,3,4,5])
print(np.average(x,weights=w))

3.6666666666666665

In [ ]:
#trimmed mean
#1 2 3 4 5 6 7 8 9 10
#trim value 10%
#2 3 4 5 6 7 8 9
print(np.array([2,3,4,5,6,7,8,9]).mean())

5.5

In [ ]:
weights=np.array([.2,.3,.4,.5,.6,.7,.8,.9])
print(np.sum(weights))
np.cumsum(weights)

4.4

array([0.2, 0.5, 0.9, 1.4, 2. , 2.7, 3.5, 4.4])

In [ ]:
#trimmed mean
#1 2 3 4 5 6 7 8 9 10
#trim value 10%
#2 3 4 5 6 7 8 9
x=np.arange(1,10)
print(x)
y=x/10
print(y)
trim_len=int(len(x)/10)+1
print(trim_len)
x=x[trim_len:len(x)-trim_len]
print(x)
print(np.mean(x))

[1 2 3 4 5 6 7 8 9]
[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
1
[2 3 4 5 6 7 8]
5.0

In [ ]:
#excercise 1
store1_sales=np.array([10,15,20,13,17])
store2_sales=np.array([12,18,25,11,16])

In [ ]:
#element wise sum
print(np.add(store1_sales,store2_sales))

[22 33 45 24 33]

In [ ]:
print(np.multiply(store1_sales,store2_sales))

[120 270 500 143 272]

In [ ]:
print(np.subtract(store1_sales,store2_sales))

[-2 -3 -5  2  1]

In [ ]:
print(np.sum(store1_sales+store2_sales))

157

In [ ]:
angles=np.array([0,30,45,60,90])
num=np.array([24,36,18,48,60])
num2=np.array([18,60,24,36,12])
np.deg2rad(angles)

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [ ]:
np.sin(np.deg2rad(angles))

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [ ]:
np.cos(np.deg2rad(angles))

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [ ]:
np.gcd(num,num2)

array([ 6, 12,  6, 12, 12])

In [ ]:
np.lcm(num,num2)

array([ 72, 180,  72, 144,  60])

In [ ]:
np.gcd.reduce(num)
np

6

In [ ]:
np.lcm.reduce(num2)

360

In [ ]:
np.lcm(np.lcm.reduce(num),np.lcm.reduce(num2))

720

In [ ]:
np.gcd(np.gcd.reduce(num),np.gcd.reduce(num2))

6

#pandas

In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [ ]:
import pandas as pd

In [ ]:
print(pd.__version__)

2.2.2

In [ ]:
#data structures and i/o operations
#seris-1D array, data frame-2D array
a=pd.series([1,2,3,4,5])
print(a)

AttributeError: module 'pandas' has no attribute 'series'

In [ ]:
df=pd.read_csv('/car_data.csv')
print(df.to_string())

     city_mpg                           class  combination_mpg  cylinders  displacement drive    fuel_type  highway_mpg               make                                  model transmission  year
0          25                     midsize car               29        4.0           2.5   fwd          gas           36              mazda                                      6            m  2014
1          26                     midsize car               30        4.0           2.5   fwd          gas           37              mazda                                      6            a  2014
2          25     small sport utility vehicle               27        4.0           2.5   fwd          gas           31              mazda                               cx-5 2wd            a  2014
3          26     small sport utility vehicle               29        4.0           2.0   fwd          gas           34              mazda                               cx-5 2wd            m  2014
4          26     small sport utility vehicle               28        4.0           2.0   fwd          gas           32              mazda                               cx-5 2wd            a  2014
5          24     small sport utility vehicle               26        4.0           2.5   4wd          gas           29              mazda                               cx-5 4wd            a  2014
6          25     small sport utility vehicle               27        4.0           2.0   4wd          gas           30              mazda                               cx-5 4wd            a  2014
7          19                  subcompact car               22        6.0           3.7   rwd          gas           29               ford                                mustang            m  2014
8          19                  subcompact car               23        6.0           3.7   rwd          gas           30               ford                                mustang            a  2014
9          15                  subcompact car               18        8.0           5.8   rwd          gas           24               ford                                mustang            m  2014
10         18                  subcompact car               20        8.0           5.0   rwd          gas           25               ford                                mustang            a  2014
11         22     small sport utility vehicle               24        4.0           2.5   awd          gas           28             subaru                           forester awd            m  2014
12         24     small sport utility vehicle               27        4.0           2.5   awd          gas           31             subaru                           forester awd            a  2014
13         23     small sport utility vehicle               25        4.0           2.0   awd          gas           27             subaru                           forester awd            a  2014
14         19                  subcompact car               23        6.0           3.7   rwd          gas           29               ford                    mustang convertible            a  2014
15         16                  subcompact car               19        8.0           5.0   rwd          gas           25               ford                                mustang            m  2014
16         16                  subcompact car               19        6.0           3.8   awd          gas           23             nissan                                   gt-r            a  2014
17         24                       large car               28        6.0           3.0   awd       diesel           36               audi                                   a8 l            a  2014
18         20     small sport utility vehicle               22        4.0           2.4   fwd          gas           26                kia                            sorento 2wd            a  2014
19         19     small sport utility vehicle               21        4.0           2.4   fwd          gas           27                kia                            sorento 2wd            m  2014
20         18     small sport utility vehicle               21        6.0           3.3   fwd          gas           25                kia                            sorento 2wd            a  2014
21         19     small sport utility vehicle               21        4.0           2.4   4wd          gas           24                kia                            sorento 4wd            a  2014
22         18     small sport utility vehicle               20        6.0           3.3   4wd          gas           23                kia                            sorento 4wd            a  2014
23         17     small sport utility vehicle               19        6.0           3.5   awd          gas           22             nissan                  murano crosscabriolet            a  2014
24         13                      two seater               16       10.0           5.2   awd          gas           22               audi                              r8 spyder            a  2014
25         13                      two seater               16       10.0           5.2   awd          gas           22               audi                                     r8            a  2014
26         14                      two seater               17        8.0           4.2   awd          gas           23               audi                              r8 spyder            a  2014
27         14                      two seater               17        8.0           4.2   awd          gas           23               audi                                     r8            a  2014
28         12                      two seater               14       10.0           5.2   awd          gas           19               audi                              r8 spyder            m  2014
29         12                      two seater               14       10.0           5.2   awd          gas           19               audi                                     r8            m  2014
30         11                      two seater               14        8.0           4.2   awd          gas           20               audi                              r8 spyder            m  2014
31         11                      two seater               14        8.0           4.2   awd          gas           20               audi                                     r8            m  2014
32         13                 minicompact car               15       12.0           5.9   rwd          gas           19       aston martin                                    db9            a  2014
33         13                 minicompact car               15       12.0           5.9   rwd          gas           19       aston martin                               vanquish            a  2014
34         13                  subcompact car               15       12.0           5.9   rwd          gas           19       aston martin                               rapide s            a  2014
35         14                  subcompact car               17        8.0           5.0   rwd          gas           22  roush performance                        stage 3 mustang            m  2014
36         21     small sport utility vehicle               24        4.0           2.4   fwd          gas           28               jeep                            compass fwd            a  2014
37         21     small sport utility vehicle               24        4.0           2.4   fwd          gas           28               jeep                            patriot fwd            a  2014
38         21     small sport utility vehicle               24        4.0           2.0   fwd          gas           28               jeep                            compass fwd            a  2014
39         21     small sport utility vehicle               24        4.0           2.0   fwd          gas           28               jeep                            patriot fwd            a  2014
40         23     small sport utility vehicle               25        4.0           2.4   fwd          gas           28               jeep                            patriot fwd            m  2014
41         23     small sport utility vehicle               25        4.0           2.4   fwd          gas           28               jeep                            compass fwd            m  2014
42         23     small sport utility vehicle               25        4.0           2.0   fwd          gas           30               jeep                            compass fwd            m  2014
43         21     small sport utility vehicle               23        4.0           2.4   4wd          gas           27               jeep                            compass 4wd            a  2014
44         21     small sport utility vehicle               23        4.0           2.4   4wd          gas           27               jeep                            patriot 4wd            a  2014
45         23     small sport utility vehicle               25        4.0           2.4   4wd          gas           28               jeep                            compass 4wd            m  2014
46         23     small sport utility vehicle               25        4.0           2.4   4wd          gas           28               jeep                            patriot 4wd            m  2014
47         13  standard sport utility vehicle               15        8.0           6.4   4wd          gas           19               jeep                    grand cherokee srt8            a  2014
48         14  standard sport utility vehicle               17        8.0           4.8   awd          gas           21            porsche                          cayenne turbo            a  2014
49         15                  subcompact car               17        8.0           5.0   rwd          gas           22  roush performance                        stage 3 mustang            a  2014
50         16                  subcompact car               19        6.0           3.8   awd          gas           23             nissan                                   gt-r            a  2015
51         20                     compact car               23        5.0           2.5   awd          gas           28              volvo                                s60 awd            a  2015
52         26                     midsize car               30        4.0           2.5   fwd          gas           37              mazda                                      6            a  2015
53         28                     midsize car               32        4.0           2.5   fwd          gas           39              mazda                                      6            a  2015
54         25                     midsize car               29        4.0           2.5   fwd          gas           35              mazda                                      6            m  2015
55         18                       large car               21        6.0           3.8   rwd          gas           26                kia                                   k900            a  2015
56         15                       large car               18        8.0           5.0   rwd          gas           23                kia                                   k900            a  2015
57         18     small sport utility vehicle               21        6.0           3.3   fwd          gas           25                kia                            sorento fwd            a  2015
58         26     small sport utility vehicle               28        4.0           2.0   fwd          gas           32              mazda                               cx-5 2wd            a  2015
59         26     small sport utility vehicle               29        4.0           2.0   fwd          gas           34              mazda                               cx-5 2wd            m  2015
60         25     small sport utility vehicle               27        4.0           2.5   fwd          gas           31              mazda                               cx-5 2wd            a  2015
61         19     small sport utility vehicle               21        4.0           2.4   awd          gas           25                kia                            sorento awd            a  2015
62         18     small sport utility vehicle               20        6.0           3.3   awd          gas           23                kia                            sorento awd            a  2015
63         25     small sport utility vehicle               27        4.0           2.0   4wd          gas           30              mazda                               cx-5 4wd            a  2015
64         24     small sport utility vehicle               26        4.0           2.5   4wd          gas           29              mazda                               cx-5 4wd            a  2015
65         17     small sport utility vehicle               20        6.0           3.0   awd          gas           24              volvo                               xc60 awd            a  2015
66         17     small sport utility vehicle               20        6.0           3.0   awd          gas           24              volvo                               xc70 awd            a  2015
67         22                      two seater               26        4.0           2.0   awd          gas           31               audi                    tt roadster quattro            a  2015
68         22                  subcompact car               26        4.0           2.0   awd          gas           31               audi                       tt coupe quattro            a  2015
69         21                     compact car               24        4.0           2.0   awd          gas           28             subaru                                    wrx            m  2015
70         17                     compact car               19        4.0           2.5   awd          gas           23             subaru                                    wrx            m  2015
71         19                     compact car               22        6.0           3.0   awd          gas           28              volvo                                s60 awd            a  2015
72         19                     midsize car               22        6.0           3.0   awd          gas           28              volvo                                s80 awd            a  2015
73         20             small station wagon               23        5.0           2.5   awd          gas           28              volvo                                v60 awd            a  2015
74         19             small station wagon               22        6.0           3.0   awd          gas           28              volvo                                v60 awd            a  2015
75         16           standard pickup truck               19        8.0           5.3   rwd          gas           23          chevrolet                      silverado c15 2wd            a  2015
76         16           standard pickup truck               19        8.0           5.3   rwd          gas           23                gmc                         sierra c15 2wd            a  2015
77         16           standard pickup truck               18        8.0           5.3   4wd          gas           22          chevrolet                      silverado k15 4wd            a  2015
78         16           standard pickup truck               18        8.0           5.3   4wd          gas           22                gmc                         sierra k15 4wd            a  2015
79         20     small sport utility vehicle               23        4.0           2.4   fwd          gas           27                kia                            sorento fwd            a  2015
80         15  standard sport utility vehicle               17        8.0           6.2   rwd          gas           21           cadillac                           escalade 2wd            a  2015
81         15  standard sport utility vehicle               17        8.0           6.2   rwd          gas           21           cadillac                       escalade esv 2wd            a  2015
82         16  standard sport utility vehicle               18        8.0           5.3   rwd          gas           23          chevrolet                        tahoe c1500 2wd            a  2015
83         16  standard sport utility vehicle               18        8.0           5.3   rwd          gas           23          chevrolet                     suburban c1500 2wd            a  2015
84         15  standard sport utility vehicle               17        8.0           6.2   rwd          gas           21                gmc                        yukon c1500 2wd            a  2015
85         15  standard sport utility vehicle               17        8.0           6.2   rwd          gas           21                gmc                     yukon c1500 xl 2wd            a  2015
86         16  standard sport utility vehicle               18        8.0           5.3   rwd          gas           23                gmc                        yukon c1500 2wd            a  2015
87         16  standard sport utility vehicle               18        8.0           5.3   rwd          gas           23                gmc                     yukon c1500 xl 2wd            a  2015
88         14  standard sport utility vehicle               16        8.0           6.2   4wd          gas           21           cadillac                           escalade 4wd            a  2015
89         14  standard sport utility vehicle               16        8.0           6.2   4wd          gas           20           cadillac                       escalade esv 4wd            a  2015
90         16  standard sport utility vehicle               18        8.0           5.3   4wd          gas           22          chevrolet                        tahoe k1500 4wd            a  2015
91         15  standard sport utility vehicle               18        8.0           5.3   4wd          gas           22          chevrolet                     suburban k1500 4wd            a  2015
92         14  standard sport utility vehicle               16        8.0           6.2   4wd          gas           20                gmc                     yukon k1500 xl 4wd            a  2015
93         14  standard sport utility vehicle               16        8.0           6.2   4wd          gas           21                gmc                        yukon k1500 4wd            a  2015
94         15  standard sport utility vehicle               18        8.0           5.3   4wd          gas           22                gmc                     yukon k1500 xl 4wd            a  2015
95         16  standard sport utility vehicle               18        8.0           5.3   4wd          gas           22                gmc                        yukon k1500 4wd            a  2015
96         16                      two seater               18        8.0           5.0   rwd          gas           23             jaguar                f-type v8 s convertible            a  2015
97         16                      two seater               18        8.0           5.0   rwd          gas           23             jaguar                         f-type r coupe            a  2015
98         20                      two seater               23        6.0           3.0   rwd          gas           28             jaguar                     f-type convertible            a  2015
99         20                      two seater               23        6.0           3.0   rwd          gas           28             jaguar                           f-type coupe            a  2015

In [ ]:
a=[1,2,3]
a=pd.Series(a)
print(a)
#

0    1
1    2
2    3
dtype: int64

In [ ]:
#customise indexing
a=[2,4,5]
a=pd.Series(a,index=['a1','a2','a3'])
print(a)

a1    2
a2    4
a3    5
dtype: int64

In [ ]:
print(df[4:5])
print(df.loc[4])

   city_mpg                        class  combination_mpg  cylinders  \
4        26  small sport utility vehicle               28        4.0

   displacement drive fuel_type  highway_mpg   make     model transmission  \
4           2.0   fwd       gas           32  mazda  cx-5 2wd            a

   year
4  2014
city_mpg                                    26
class              small sport utility vehicle
combination_mpg                             28
cylinders                                  4.0
displacement                               2.0
drive                                      fwd
fuel_type                                  gas
highway_mpg                                 32
make                                     mazda
model                                 cx-5 2wd
transmission                                 a
year                                      2014
Name: 4, dtype: object

In [ ]:
df.loc[4,"fuel_type"]

'gas'

In [ ]:
df.head()

,city_mpg,class,combination_mpg,cylinders,displacement,drive,fuel_type,highway_mpg,make,model,transmission,year
0,25,midsize car,29,4.0,2.5,fwd,gas,36,mazda,6,m,2014
1,26,midsize car,30,4.0,2.5,fwd,gas,37,mazda,6,a,2014
2,25,small sport utility vehicle,27,4.0,2.5,fwd,gas,31,mazda,cx-5 2wd,a,2014
3,26,small sport utility vehicle,29,4.0,2.0,fwd,gas,34,mazda,cx-5 2wd,m,2014
4,26,small sport utility vehicle,28,4.0,2.0,fwd,gas,32,mazda,cx-5 2wd,a,2014

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550 entries, 0 to 549
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   city_mpg         550 non-null    int64
 1   class            550 non-null    object
 2   combination_mpg  550 non-null    int64
 3   cylinders        548 non-null    float64
 4   displacement     548 non-null    float64
 5   drive            550 non-null    object
 6   fuel_type        550 non-null    object
 7   highway_mpg      550 non-null    int64
 8   make             550 non-null    object
 9   model            550 non-null    object
 10  transmission     550 non-null    object
 11  year             550 non-null    int64
dtypes: float64(2), int64(4), object(6)
memory usage: 51.7+ KB

In [ ]:
data={"country":["india","china","usa"],"population":[100,234,233],"Area":[200,123,345],"Gdp":[123,345,567]}
dp=pd.DataFrame(data)
print(dp)

  country  population  Area  Gdp
0   india         100   200  123
1   china         234   123  345
2     usa         233   345  567

In [ ]:
print(dp['population'].info())

<class 'pandas.core.series.Series'>
RangeIndex: 3 entries, 0 to 2
Series name: population
Non-Null Count  Dtype
--------------  -----
3 non-null      int64
dtypes: int64(1)
memory usage: 152.0 bytes
None

In [ ]:
dp.head(5)

  country  population  Area  Gdp
0   india         100   200  123
1   china         234   123  345
2     usa         233   345  567

In [ ]:
dp['Gdp'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 3 entries, 0 to 2
Series name: Gdp
Non-Null Count  Dtype
--------------  -----
3 non-null      int64
dtypes: int64(1)
memory usage: 152.0 bytes

In [ ]:
dp.tail(5)

  country  population  Area  Gdp
0   india         100   200  123
1   china         234   123  345
2     usa         233   345  567

In [ ]:
dp.loc[1,'country']=None
dp

  country  population  Area  Gdp
0   india         100   200  123
1    None         234   123  345
2     usa         233   345  567

In [ ]:
dp=dp.dropna() #creates a temp deletion

In [ ]:
dp

  country  population  Area  Gdp
0   india         100   200  123
2     usa         233   345  567

In [ ]:
#adding new columns
dp['cddf']=pd.Series(['fdf','sfdsd'],index=[0,2])

<ipython-input-68-6306a5b36be5>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dp['cddf']=pd.Series(['fdf','sfdsd'],index=[0,2])

In [ ]:
dp

  country  population  Area  Gdp   cddf
0   india         100   200  123    fdf
2     usa         233   345  567  sfdsd

In [ ]:
#permanent deletion
dp.dropna(inplace=True)

<ipython-input-70-d156ad3d4363>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dp.dropna(inplace=True)

In [ ]:
dp

  country  population  Area  Gdp   cddf
0   india         100   200  123    fdf
2     usa         233   345  567  sfdsd

In [ ]:
#fill null values
dp.fillna(100,inplace=True)

<ipython-input-72-97f757ff262c>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dp.fillna(100,inplace=True)

In [ ]:
dp

  country  population  Area  Gdp   cddf
0   india         100   200  123    fdf
2     usa         233   345  567  sfdsd